/* ==========================================================================
   fileira-base.js — as 18 lições da primeira trilha.

   Teclas: a s d f g h j k l — a posição de descanso das mãos.

   POR QUE ESTA TRILHA É DO JEITO QUE É

   Destas nove letras, a única vogal é o A. Sem ele não existe palavra
   nenhuma em português, então o A entra na lição 5 e as palavras só
   aparecem a partir dali. Todas as palavras possíveis têm só a letra A
   como vogal — são 36 no total, e todas aparecem nesta trilha.

   O K não tem uma única palavra possível aqui: o português quase não usa
   essa letra, e as poucas exceções (kiwi, karatê) precisam de letras de
   outras fileiras. Por isso o K aparece só em exercícios de sílabas. É
   honesto: melhor treinar o dedo do que inventar palavra que não existe.

   As frases das lições 14, 15, 17 e 18 são português correto, mas de
   sentido meio absurdo — consequência de existir só a vogal A. Elas estão
   aí porque uma lição de frases precisa treinar o espaço entre palavras e
   o ritmo de escrever, não só teclas soltas.

   COMO EDITAR

   Ver MODELO.md nesta pasta. Duas conferências automáticas rodam sobre
   este arquivo (conferencia.js) e avisam no console se alguma lição usar
   uma letra que ainda não foi ensinada ou que não existe no teclado
   escolhido — então mexer aqui é seguro.
   ========================================================================== */

export const fileiraBase = [
  /* --- Aprendendo as teclas, aos pares ---------------------------------- */

  {
    id: 'base-01',
    tipo: 'teclas-novas',
    titulo: { pt: 'F e J: o ponto de partida', en: 'F and J: the starting point' },
    teclasNovas: ['f', 'j'],
    conteudo: [
      'fff jjj fff jjj fff jjj',
      'ff jj ff jj ff jj ff jj',
      'fj fj fj jf jf jf',
      'fjf jfj fjf jfj fjf',
      'ffj jjf ffj jjf ffj',
      'jjj fff jjj fff jjj',
      'jf jf jf fj fj fj',
      'jfj fjf jfj fjf jfj',
      'fjj jff fjj jff fjj',
      'fj jf fjf jfj ffj jjf',
      'ff jj fj jf ffj jjf',
      'fjf jfj fjj jff fj jf',
    ],
  },
  {
    id: 'base-02',
    tipo: 'teclas-novas',
    titulo: { pt: 'D e K', en: 'D and K' },
    teclasNovas: ['d', 'k'],
    conteudo: [
      'ddd kkk ddd kkk ddd kkk',
      'dd kk dd kk dd kk dd kk',
      'dk dk dk kd kd kd',
      'dkd kdk dkd kdk dkd',
      'fd jk fd jk fd jk',
      'dfd kjk dfd kjk dfd',
      'kkk ddd kkk ddd kkk',
      'kd kd kd dk dk dk',
      'kdk dkd kdk dkd kdk',
      'fdk jkd fdk jkd fdk',
      'df kj df kj dk kd',
      'dkd kdk fdk jkd dk kd',
    ],
  },
  {
    id: 'base-03',
    tipo: 'revisao',
    titulo: { pt: 'Revisão: F J D K', en: 'Review: F J D K' },
    teclasNovas: [],
    conteudo: [
      'fj dk fj dk fj dk',
      'fdjk fdjk fdjk fdjk',
      'jkdf jkdf jkdf jkdf',
      'dkfj kdjf dkfj kdjf',
      'ffjj ddkk ffjj ddkk',
      'fjdk jfkd dfkj kdfj',
      'df jk fd kj df jk',
      'fjf dkd jfj kdk fjf',
      'kjkj dfdf kjkj dfdf',
      'fdk jkd dkf kdj fjd',
      'jk df kj fd jk df',
      'fjdk fjdk jkdf jkdf',
    ],
  },
  {
    id: 'base-04',
    tipo: 'teclas-novas',
    titulo: { pt: 'S e L', en: 'S and L' },
    teclasNovas: ['s', 'l'],
    conteudo: [
      'sss lll sss lll sss lll',
      'ss ll ss ll ss ll ss ll',
      'sl sl sl ls ls ls',
      'sls lsl sls lsl sls',
      'sd lk sd lk sd lk',
      'dsd klk dsd klk dsd',
      'lll sss lll sss lll',
      'ls ls ls sl sl sl',
      'lsl sls lsl sls lsl',
      'fsl jkl fsl jkl fsl',
      'sdf jkl sdf jkl sdf',
      'sl ls sls lsl fsl jkl',
    ],
  },

  /* --- A vogal: aqui começam as palavras -------------------------------- */

  {
    id: 'base-05',
    tipo: 'teclas-novas',
    titulo: { pt: 'A: a primeira vogal', en: 'A: the first vowel' },
    teclasNovas: ['a'],
    conteudo: [
      'aaa aaa aaa aaa',
      'aa aa aa aa aa aa',
      'sa la fa da sa la fa da',
      'as as as as as as',
      'asa asa asa asa',
      'ala ala ala ala',
      'ada ada afa afa',
      'aka aja aka aja',
      'as da as da as da',
      'asa ala asa ala asa',
      'sala sala sala',
      'fala fala fala',
      'asa ala sala fala',
    ],
  },
  {
    id: 'base-06',
    tipo: 'palavras',
    titulo: { pt: 'Primeiras palavras', en: 'First words' },
    teclasNovas: [],
    conteudo: [
      'asa asas ala alas',
      'as da das as da das',
      'asa da ala das asa',
      'asas alas asas alas',
      'as asas das alas',
      'ala asa das asas ala',
      'asa asas ala alas as',
      'da das da das asa ala',
      'alas asas alas asas',
      'as ala das asa da alas',
      'asa ala as da das alas',
      'asas alas asa ala das',
    ],
  },
  {
    id: 'base-07',
    tipo: 'palavras',
    titulo: { pt: 'Sala, fala, fada', en: 'Sala, fala, fada' },
    teclasNovas: [],
    conteudo: [
      'sala sala fala fala',
      'fada fada dada dada',
      'salsa salsa salsa',
      'sala fala fada dada',
      'salsa fada sala fala',
      'fala sala dada salsa',
      'fada sala salsa fala',
      'dada dadas fada fadas',
      'sala salsa sala salsa',
      'fala fada sala dada',
      'salsa sala fala fada',
      'sala fala fada dada salsa',
    ],
  },
  {
    id: 'base-08',
    tipo: 'revisao',
    titulo: { pt: 'Revisão: sete teclas', en: 'Review: seven keys' },
    teclasNovas: [],
    conteudo: [
      'kjk dkd kjk dkd kjk',
      'sala kkk fala kkk',
      'asa jkl ala fds',
      'fada kdk dada kjk',
      'as das salsa falsa',
      'falsa falsas falsa',
      'sala fala fada dada asa',
      'jkl fds jkl fds',
      'kdk jfj kdk jfj',
      'salsa falsa alas asas',
      'as da das asa ala',
      'sala falsa fala salsa',
    ],
  },

  /* --- As duas últimas teclas: G e H ------------------------------------ */

  {
    id: 'base-09',
    tipo: 'teclas-novas',
    titulo: { pt: 'G e H: esticando o indicador', en: 'G and H: stretching the index' },
    teclasNovas: ['g', 'h'],
    conteudo: [
      'ggg hhh ggg hhh ggg',
      'gg hh gg hh gg hh',
      'gh gh gh hg hg hg',
      'fg jh fg jh fg jh',
      'gfg hjh gfg hjh gfg',
      'fgh jhg fgh jhg fgh',
      'hhh ggg hhh ggg hhh',
      'hg hg hg gh gh gh',
      'hjh gfg hjh gfg hjh',
      'ga ha ga ha ga ha',
      'aga aha aga aha',
      'gh hg ghg hgh fgh jhg',
    ],
  },
  {
    id: 'base-10',
    tipo: 'palavras',
    titulo: { pt: 'Palavras com G', en: 'Words with G' },
    teclasNovas: [],
    conteudo: [
      'gala gala saga saga',
      'alga algas alfa alfa',
      'adaga adagas afaga',
      'gala saga alga alfa',
      'adaga afaga gala saga',
      'saga gala alga adaga',
      'algas adagas alfa gala',
      'afaga adaga afaga adaga',
      'saga sagas gala alga',
      'alfa alga algas adaga',
      'gala saga adaga afaga',
      'alga alfa saga gala adaga',
    ],
  },
  {
    id: 'base-11',
    tipo: 'palavras',
    titulo: { pt: 'Palavras com H', en: 'Words with H' },
    teclasNovas: [],
    conteudo: [
      'falha falhas falha',
      'haja haja ah ah',
      'falha haja ah falha',
      'ah falha ah falhas',
      'haja falha haja falhas',
      'ah ah haja falha',
      'falhas falha falhas',
      'haja ah haja ah',
      'falha haja falhas ah',
      'aha aha haja haja',
      'ah falha haja falhas',
      'falha falhas haja ah',
    ],
  },
  {
    id: 'base-12',
    tipo: 'palavras',
    titulo: { pt: 'Palavras longas', en: 'Longer words' },
    teclasNovas: [],
    conteudo: [
      'salada saladas',
      'salgada salgadas',
      'falada faladas',
      'assada assadas',
      'alada aladas assa',
      'salada salgada falada',
      'assada alada salada',
      'saladas salgadas faladas',
      'assa assada assadas',
      'alada aladas salada',
      'salgada salada assada',
      'falada salgada alada assa',
    ],
  },
  {
    id: 'base-13',
    tipo: 'revisao',
    titulo: { pt: 'Revisão: as nove teclas', en: 'Review: all nine keys' },
    teclasNovas: [],
    conteudo: [
      'asdf jkl gh asdf jkl',
      'fj dk sl gh a fj dk',
      'asa sala fada gala',
      'alga haja falha adaga',
      'salada salgada assada',
      'kjk ghg fjf dkd sls',
      'ala alfa saga assa',
      'das falsa salsa alas',
      'afaga adaga alada falada',
      'ah as da haja fada',
      'ghg kjk sls dkd fjf',
      'sala salada salgada asa',
    ],
  },

  /* --- Frases: o espaço entre palavras e o ritmo ------------------------- */

  {
    id: 'base-14',
    tipo: 'frases',
    titulo: { pt: 'Primeiras frases', en: 'First sentences' },
    teclasNovas: [],
    conteudo: [
      'a fada fala',
      'as asas da fada',
      'a sala salgada',
      'a alga salgada',
      'a fala falsa',
      'a saga da fada',
      'a salada da fada',
      'as alas da sala',
      'a fada afaga',
      'a salsa salgada',
      'as asas aladas',
      'a adaga falsa',
      'a sala das fadas',
      'a saga das algas',
    ],
  },
  {
    id: 'base-15',
    tipo: 'frases',
    titulo: { pt: 'Frases mais longas', en: 'Longer sentences' },
    teclasNovas: [],
    conteudo: [
      'a salada salgada',
      'as asas aladas da fada',
      'a saga das algas',
      'a fada afaga as asas',
      'a fala falsa da fada',
      'as saladas assadas',
      'a fada fala das algas',
      'a sala da salada salgada',
      'as adagas falsas da saga',
      'a alga assada da sala',
      'as fadas faladas',
      'a fada salgada afaga as asas',
    ],
  },
  {
    id: 'base-16',
    tipo: 'palavras',
    titulo: { pt: 'Ritmo e velocidade', en: 'Rhythm and speed' },
    teclasNovas: [],
    conteudo: [
      'asa ala sala fala fada',
      'gala saga alga alfa adaga',
      'falha haja salsa falsa',
      'salada salgada falada assada',
      'dada alada assa afaga',
      'as da das ah',
      'asas alas salas falas',
      'fadas sagas algas adagas',
      'falhas saladas aladas',
      'salgadas faladas assadas',
      'asa sala gala haja alfa',
      'fada alga adaga falha salsa',
    ],
  },
  {
    id: 'base-17',
    tipo: 'revisao',
    titulo: { pt: 'Revisão final', en: 'Final review' },
    teclasNovas: [],
    conteudo: [
      'fjf dkd sls ghg kjk',
      'asa sala fada gala haja',
      'salada salgada assada alada',
      'a fada fala',
      'a saga das algas',
      'as asas da fada',
      'alga alfa adaga afaga',
      'falsa falha salsa dada',
      'a salada salgada',
      'as fadas faladas',
      'kjk ghg fjf dkd sls',
      'a fada afaga as asas',
    ],
  },
  {
    id: 'base-18',
    tipo: 'desafio',
    titulo: { pt: 'Desafio da fileira base', en: 'Home row challenge' },
    teclasNovas: [],
    conteudo: [
      'asa ala sala fala fada gala',
      'alga alfa saga adaga afaga',
      'falha haja salsa falsa salada',
      'salgada falada assada alada',
      'a fada afaga as asas',
      'a salada salgada da sala',
      'as asas aladas da fada',
      'a saga das algas',
      'as adagas falsas',
      'fjf dkd sls ghg kjk',
      'asas alas fadas sagas algas',
      'a fala falsa da fada',
    ],
  },
];
